
services:
  ml-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./app:/app/app
    environment:
      - FLASK_ENV=development
    restart: unless-stopped